### ISSUE TITLE
AromaBackup

### ISSUE THREAD

**Issue by Romz24** [glitchless/MinecraftServerLocalization#1]
Я установил ваш мод чтобы изменить на сервере язык для мода [AromaBackup](https://www.curseforge.com/minecraft/mc-mods/aromabackup) так как там имеется языковой файл **ru_RU.lang**, но сообщения на сервере все равно отправляются на английском языке. Вы можете добавить поддержку этого мода?

**Comment by LionZXY** [comment]
Можно

**Comment by LionZXY** [comment]
Оно точно автоматом не меняется? Я посмотрел, все должно работать прям так, но в самом моде очень мало элементов переведено

**Comment by Romz24** [comment]
Автоматически не меняет. Мне приходится переносить перевод из **ru_ru.lang** в файл **en_us.lang**, что собственно не удобно совершенно.

**Comment by LionZXY** [comment]
У меня все заменило на тестовом сервере. Как будет время, посмотрю

**Comment by Romz24** [comment]
Возможно это зависит от ядра? Я использую ванильное ядро + forge-1.12.2-14.23.5.2847

**Comment by Romz24** [comment]
Заметил что аналогично перевод не работает для мода [Extra Planets](https://www.curseforge.com/minecraft/mc-mods/extraplanets), при том что в комплекте с модом идет файл ru_RU.lang

![image](https://user-images.githubusercontent.com/2458113/71426488-541abe00-26bb-11ea-8c04-3dd1ebf195c3.png)

Перед тем как писать сообщение я проверил одиночную игру, там перевод работает без проблем.

**Comment by Romz24** [comment]
Логи:

```
[02:12:34] [Server thread/INFO] [serverlocalization]: Applying lang for VanillaChanger
[02:12:34] [Server thread/INFO] [serverlocalization]: Change lang to ru_ru for vanilla done!
[02:12:34] [Server thread/INFO] [serverlocalization]: Applying lang for OtherModChanger
[02:12:34] [Server thread/INFO] [serverlocalization]: Applying lang for IC2LangChanger
[02:12:34] [Server thread/INFO] [serverlocalization]: Change lang to ru_ru for ic2 done!
```
